### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by Osinedges** [Cultti/webrcon-cli#8]
Hi there, I found the following issue when connecting to an ark server via rcon,
I will emit my IP & Password but this is my command:
`webrcon-cli 100.100.100.100:25000 randomPassword "Broadcast Hello Server"`

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:332:15)
    at Socket.socketOnEnd (_http_client.js:435:23)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at WebSocket.<anonymous> (/usr/local/lib/node_modules/webrcon-cli/dist/lib/webrcon.js:59:27)
    at WebSocket.emit (events.js:198:13)
    at WebSocket.finalize (/usr/local/lib/node_modules/webrcon-cli/node_modules/ws/lib/websocket.js:185:12)
    at ClientRequest._req.on (/usr/local/lib/node_modules/webrcon-cli/node_modules/ws/lib/websocket.js:635:10)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketOnEnd (_http_client.js:435:9)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I am sure I've done everything right. Am happy to help with testing

**Comment by Cultti** [comment]
Hi,

Sorry for the late reply. Haven't been checking Github lately 😅.

I can't find documentation if Ark is using webrcon or not. There is support at least for 'normal' rcon. So this tool might not work.
